import Config

# OAuth provider credentials for development.
# Set these environment variables or replace with your dev app credentials.
# Google: https://console.cloud.google.com/apis/credentials
# GitHub: https://github.com/settings/developers
#
# Redirect URIs to register with each provider:
#   Google:  http://localhost:4000/auth/google/callback
#   GitHub:  http://localhost:4000/auth/github/callback
# Anthropic API key for claim/edge extraction.
# Set ANTHROPIC_API_KEY in your environment or replace nil with a string for local dev.
config :xwa, :anthropic_api_key, System.get_env("ANTHROPIC_API_KEY")

# Claude models for ingestion. Claim extraction uses Sonnet for quality;
# edge extraction uses Haiku (cheaper/faster — the hard semantic work is done by then).
config :xwa, :claude_claim_model, "claude-sonnet-4-6"
config :xwa, :claude_edge_model,  "claude-haiku-4-5-20251001"

config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: System.get_env("GOOGLE_CLIENT_ID"),
  client_secret: System.get_env("GOOGLE_CLIENT_SECRET")

config :ueberauth, Ueberauth.Strategy.Github.OAuth,
  client_id: System.get_env("GITHUB_CLIENT_ID"),
  client_secret: System.get_env("GITHUB_CLIENT_SECRET")

# Configure Memgraph connection via Bolt protocol (bolt_sips)
config :bolt_sips, Bolt,
  url: "bolt://localhost:7687",
  pool_size: 10,
  prefix: :default

# Configure your database
config :xwa, Xwa.Repo,
  username: System.get_env("XWA_DB_USER") || "xwa",
  password: System.get_env("XWA_DB_PASSWORD") || raise("XWA_DB_PASSWORD env var not set"),
  hostname: System.get_env("XWA_DB_HOST") || "localhost",
  database: System.get_env("XWA_DB_NAME") || "xwa",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :xwa, XwaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lUwDsOUT1mOYCoCCktGjEzqbn0aM+wTKwdsC422mj+57rICnufc0987oUThCgAXQ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:xwa, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:xwa, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :xwa, XwaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/xwa_web/router\.ex$"E,
      ~r"lib/xwa_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :xwa, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
