defmodule Xwa.Graph.Node do
  @moduledoc """
  Struct representing a Claim node in the Memgraph knowledge graph.

  This is not an Ecto schema — it maps to a Memgraph node with the
  `:Claim` label. Postgres only holds document metadata; all claim
  data lives in the graph.

  ## Field notes

  - `id` is a UUID string generated by XWA, not Memgraph's internal id.
    This is what `source_document_id` on other nodes references.
  - `embedding` is a list of floats for semantic similarity traversal.
    It is nil until the AI extraction pipeline populates it.
  - `superseded_by` is a UUID pointing to another Claim node in the graph.
    It is a property (not an edge) so the lineage chain can be traversed
    without loading full edge data. The old claim is never deleted.
  - `tags`, `validated_by`, and `shared_with` are stored as native Memgraph
    list properties.
  - `asserted_at` and `extracted_at` are ISO 8601 strings.
  - `public` controls whether the node is visible to users other than its
    creator. Defaults to true — most institutional knowledge is shared.
  - `shared_with` is a list of Postgres user UUIDs that can access this node
    when `public` is false. Has no effect when `public` is true.
  - `encrypted` signals that this node was derived from a document whose
    content is encrypted at rest in Postgres (i.e. the parent document has
    a non-nil encryption_tier). The claim content itself is stored plaintext
    in Memgraph — claims are derived, abstracted assertions, not the author's
    original work. The flag gates display and API exposure for sensitive
    documents whose claims should only be visible to authorised users.
  """

  @source_types ~w(aspirational operational external)
  @corpus_layers ~w(self_description internal_record external_context)
  @node_types ~w(claim synthesis concept)

  defstruct [
    # Identity
    :id,

    # The claim itself
    :content,
    :summary,

    # Semantics
    :type,
    :embedding,

    # Temporal
    :asserted_at,
    :extracted_at,
    :superseded_by,

    # Provenance
    :source_document_id,
    :source_type,
    :corpus_layer,

    # Audit
    :created_by,
    :notes,

    # Fields with defaults must come last
    tags: [],
    validated_by: [],
    shared_with: [],
    confidence: 1.0,
    ai_inferred: true,
    human_validated: false,
    contested: false,
    public: true,
    encrypted: false,
    # Multi-graph tenancy
    # graph_id scopes this node to a single Postgres Graph record.
    # visibility: "system"  = AI-extracted, visible to all graph members;
    #             "private" = only visible to created_by user;
    #             "shared"  = visible to members listed in shared_with (all if empty)
    graph_id: nil,
    visibility: "system",
    # Structural node type — "claim" (default), "synthesis", or "concept".
    # Synthesis nodes aggregate near-duplicate cross-graph claims; their
    # constituent source nodes are tracked via `contributes_to` edges AND
    # stored as parallel lists in Memgraph (constituent_node_ids /
    # constituent_graph_ids), which are surfaced here as `constituents`.
    node_type: "claim",
    # List of %{node_id: uuid, graph_id: uuid} maps — populated only for
    # synthesis nodes. Stored in Memgraph as parallel string lists.
    constituents: []
  ]

  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: String.t() | nil,
          summary: String.t() | nil,
          type: String.t() | nil,
          tags: [String.t()],
          embedding: [float()] | nil,
          asserted_at: String.t() | nil,
          extracted_at: String.t() | nil,
          superseded_by: String.t() | nil,
          source_document_id: String.t() | nil,
          source_type: String.t() | nil,
          corpus_layer: String.t() | nil,
          confidence: float(),
          ai_inferred: boolean(),
          human_validated: boolean(),
          contested: boolean(),
          public: boolean(),
          encrypted: boolean(),
          created_by: String.t() | nil,
          validated_by: [String.t()],
          shared_with: [String.t()],
          notes: String.t() | nil,
          graph_id: String.t() | nil,
          visibility: String.t(),
          node_type: String.t(),
          constituents: [map()]
        }

  @doc """
  Builds a new Node struct from a map of attributes, generating a UUID
  and setting `extracted_at` to now if not provided.

  Returns `{:ok, node}` or `{:error, reasons}` where reasons is a list
  of human-readable validation error strings.
  """
  @spec new(map()) :: {:ok, t()} | {:error, [String.t()]}
  def new(attrs) when is_map(attrs) do
    node = %__MODULE__{
      id: Map.get(attrs, :id) || generate_uuid(),
      content: Map.get(attrs, :content),
      summary: Map.get(attrs, :summary),
      type: Map.get(attrs, :type),
      tags: Map.get(attrs, :tags, []),
      embedding: Map.get(attrs, :embedding),
      asserted_at: Map.get(attrs, :asserted_at),
      extracted_at: Map.get(attrs, :extracted_at) || utc_now_iso(),
      superseded_by: Map.get(attrs, :superseded_by),
      source_document_id: Map.get(attrs, :source_document_id),
      source_type: Map.get(attrs, :source_type),
      corpus_layer: Map.get(attrs, :corpus_layer),
      confidence: Map.get(attrs, :confidence, 1.0),
      ai_inferred: Map.get(attrs, :ai_inferred, true),
      human_validated: Map.get(attrs, :human_validated, false),
      contested: Map.get(attrs, :contested, false),
      public: Map.get(attrs, :public, true),
      encrypted: Map.get(attrs, :encrypted, false),
      created_by: Map.get(attrs, :created_by),
      validated_by: Map.get(attrs, :validated_by, []),
      shared_with: Map.get(attrs, :shared_with, []),
      notes: Map.get(attrs, :notes),
      graph_id: Map.get(attrs, :graph_id),
      visibility: Map.get(attrs, :visibility, "system"),
      node_type: Map.get(attrs, :node_type, "claim"),
      constituents: Map.get(attrs, :constituents, [])
    }

    case validate(node) do
      [] -> {:ok, node}
      errors -> {:error, errors}
    end
  end

  @doc """
  Like `new/1` but raises on validation failure.
  """
  @spec new!(map()) :: t()
  def new!(attrs) do
    case new(attrs) do
      {:ok, node} -> node
      {:error, errors} -> raise ArgumentError, "invalid node: #{Enum.join(errors, ", ")}"
    end
  end

  @doc """
  Converts a `Bolt.Sips.Types.Node` (as returned from a Cypher query result map)
  into an `Xwa.Graph.Node` struct.

  Bolt.Sips returns node properties as a plain map with string keys inside
  the query result. Pass the properties map directly:

      {:ok, rows} = Xwa.Graph.query("MATCH (n:Claim {id: $id}) RETURN n", %{id: id})
      node = Xwa.Graph.Node.from_bolt(rows |> List.first() |> Map.get("n"))
  """
  @spec from_bolt(map()) :: t()
  def from_bolt(%Bolt.Sips.Types.Node{properties: props}) do
    from_properties(props)
  end

  def from_bolt(%{"properties" => props}) do
    from_properties(props)
  end

  def from_bolt(props) when is_map(props) do
    from_properties(props)
  end

  @doc """
  Converts the node struct into a plain map suitable for use as Cypher
  parameters. Nil values are excluded so Memgraph doesn't store null
  properties unnecessarily.
  """
  @spec to_params(t()) :: map()
  def to_params(%__MODULE__{} = node) do
    {constituents, rest} = node |> Map.from_struct() |> Map.pop(:constituents, [])

    base =
      rest
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Enum.into(%{})

    if constituents == [] do
      base
    else
      base
      |> Map.put(:constituent_node_ids, Enum.map(constituents, & &1.node_id))
      |> Map.put(:constituent_graph_ids, Enum.map(constituents, & &1.graph_id))
    end
  end

  # ---------------------------------------------------------------------------
  # Private
  # ---------------------------------------------------------------------------

  defp from_properties(props) when is_map(props) do
    %__MODULE__{
      id: props["id"],
      content: props["content"],
      summary: props["summary"],
      type: props["type"],
      tags: props["tags"] || [],
      embedding: props["embedding"],
      asserted_at: props["asserted_at"],
      extracted_at: props["extracted_at"],
      superseded_by: props["superseded_by"],
      source_document_id: props["source_document_id"],
      source_type: props["source_type"],
      corpus_layer: props["corpus_layer"],
      confidence: props["confidence"] || 1.0,
      ai_inferred: props["ai_inferred"] || true,
      human_validated: props["human_validated"] || false,
      contested: props["contested"] || false,
      public: Map.get(props, "public", true),
      encrypted: props["encrypted"] || false,
      created_by: props["created_by"],
      validated_by: props["validated_by"] || [],
      shared_with: props["shared_with"] || [],
      notes: props["notes"],
      graph_id: props["graph_id"],
      visibility: Map.get(props, "visibility", "system"),
      node_type: props["node_type"] || "claim",
      constituents: zip_constituents(props["constituent_node_ids"], props["constituent_graph_ids"])
    }
  end

  defp zip_constituents(nil, _), do: []
  defp zip_constituents([], _), do: []

  defp zip_constituents(node_ids, graph_ids) when is_list(node_ids) do
    graph_ids = graph_ids || []

    node_ids
    |> Enum.with_index()
    |> Enum.map(fn {node_id, i} ->
      %{node_id: node_id, graph_id: Enum.at(graph_ids, i)}
    end)
  end

  defp validate(%__MODULE__{} = node) do
    []
    |> require(:content, node.content)
    |> require(:summary, node.summary)
    |> then(fn errors ->
      # Synthesis nodes have no source document — they aggregate cross-graph claims
      if node.node_type == "synthesis" do
        errors
      else
        require(errors, :source_document_id, node.source_document_id)
      end
    end)
    |> validate_inclusion(:source_type, node.source_type, @source_types, allow_nil: true)
    |> validate_inclusion(:corpus_layer, node.corpus_layer, @corpus_layers, allow_nil: true)
    |> validate_inclusion(:node_type, node.node_type, @node_types, allow_nil: false)
    |> validate_confidence(node.confidence)
  end

  defp require(errors, _field, value) when is_binary(value) and value != "", do: errors
  defp require(errors, field, _), do: ["#{field} is required" | errors]

  defp validate_inclusion(errors, _field, nil, _valid, allow_nil: true), do: errors

  defp validate_inclusion(errors, field, value, valid, _opts) do
    if value in valid do
      errors
    else
      ["#{field} must be one of: #{Enum.join(valid, ", ")}" | errors]
    end
  end

  defp validate_confidence(errors, confidence)
       when is_float(confidence) and confidence >= 0.0 and confidence <= 1.0,
       do: errors

  defp validate_confidence(errors, confidence)
       when is_integer(confidence) and confidence in 0..1,
       do: errors

  defp validate_confidence(errors, _),
    do: ["confidence must be a float between 0.0 and 1.0" | errors]

  defp generate_uuid do
    Ecto.UUID.generate()
  end

  defp utc_now_iso do
    DateTime.utc_now()
    |> DateTime.truncate(:second)
    |> DateTime.to_iso8601()
  end
end
